---
http_interactions:
- request:
    method: post
    uri: https://login.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=3MVG9WtWSKUDG.x5hyqXeboVoSErlfbiCvJNDfuwmN77rRhJ6tqCeFKFhuFvMNo0COBif7CT1NnevkMq464Qp&client_secret=3920716088724079571&username=tester%2Bnetguru%40netguru.co&password=testtest12398feCLrdLjqN7Ji8zhhWf3uc
    headers:
      User-Agent:
      - Faraday v0.8.9
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 15 Apr 2014 18:25:59 GMT
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache, no-store
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: "{\"id\":\"https://login.salesforce.com/id/00D20000000CtLCEA0/005200000039DC4AAM\",\"issued_at\":\"1397586360102\",\"instance_url\":\"https://emea.salesforce.com\",\"signature\":\"BtdG8f+qXBdVwECYe53/5ZMZVa1gSLkavtl3lXClWhg=\",\"access_token\":\"00D20000000CtLC!ARcAQAsLY0P0ovgb7Y2YDUSedWjkxoSVOpwoc48GAL6v1fFWnf2AYWvrdnCV5HdaIJYE2rLaXdI7kP7XvudWLUShAm2ijeiA\"}"
    http_version: 
  recorded_at: Tue, 15 Apr 2014 18:26:00 GMT
- request:
    method: get
    uri: https://emea.salesforce.com/services/data/v26.0/query?q=select%20Id%20from%20Product2%20where%20ProductCode%20=%20'SPREE-T-SHIRT-S'
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.8.9
      Authorization:
      - OAuth 00D20000000CtLC!ARcAQAsLY0P0ovgb7Y2YDUSedWjkxoSVOpwoc48GAL6v1fFWnf2AYWvrdnCV5HdaIJYE2rLaXdI7kP7XvudWLUShAm2ijeiA
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 15 Apr 2014 18:26:00 GMT
      Sforce-Limit-Info:
      - api-usage=230/5000
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: "{\"totalSize\":1,\"done\":true,\"records\":[{\"attributes\":{\"type\":\"Product2\",\"url\":\"/services/data/v26.0/sobjects/Product2/01t20000003xwtoAAA\"},\"Id\":\"01t20000003xwtoAAA\"}]}"
    http_version: 
  recorded_at: Tue, 15 Apr 2014 18:26:01 GMT
recorded_with: VCR 2.8.0
